#!/usr/bin/env python3


from PyQt5 import QtWidgets
from PyQt5.QtWidgets import QMessageBox, QSystemTrayIcon
from PyQt5.QtGui import QIcon
from PyQt5.QtCore import QTimer
from design import Ui_MainWindow
from sys import exit
from requests import get
from os import path, remove, popen
from time import sleep
from main_selenium import allParsing, oneParsing, extraClose, listLinkOrNumbers
from threading import Thread
from notifications import checking, checkingWrite
from json import dumps, load


class myWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super(myWindow, self).__init__()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)
        self.setFocus()
        self.setGeometry(480, 55, 400, 300)

        self.click = 0
        self.color = 0
        self.timer = QTimer()
        self.timer.timeout.connect(self.timeNumber)
        self.current_path = path.dirname(path.realpath(__file__))
        self.ui.toolButton_11.setIcon(QIcon(f'{self.current_path}/icons/lamp.png'))
        self.tray = QSystemTrayIcon(self)
        self.tray.activated.connect(self.triggerFocus)
        self.tray.setToolTip(u"AnimeVostOrg - parser")
        self.tray.show()
        self.timeNumber()
        self.defaultIcon()
        self.showed()
        
        self.timer_check = QTimer()
        self.timer_check.timeout.connect(self.update)
        self.update()

        self.ui.toolButton.clicked.connect(self.saved)
        self.ui.toolButton_2.clicked.connect(self.deleted)
        self.ui.toolButton_3.clicked.connect(self.closed)
        self.ui.toolButton_4.clicked.connect(self.allDown)
        self.ui.toolButton_5.clicked.connect(self.oneDown)
        self.ui.toolButton_6.clicked.connect(extraClose)
        self.ui.toolButton_7.clicked.connect(self.loging)
        self.ui.toolButton_8.clicked.connect(self.logOne)
        self.ui.toolButton_9.clicked.connect(self.updateClick)
        self.ui.toolButton_10.clicked.connect(self.notifyCheck)
        self.ui.toolButton_11.clicked.connect(self.modeColorSheme)
        self.ui.toolButton_12.clicked.connect(self.update)


    def keyPressEvent(self, QKeyEvent):
        int_key = QKeyEvent.key()
        print(int_key)
        if int_key == 16777216:
            self.hidded()


    def uploadGlobalSettings(self):
        with open('setting.json', 'r') as r:
            data = load(r)
        return data


    def setGlobalSettings(self, to_json: dict, mode: str, var:str):
        to_json[mode] = var
        with open('setting.json', 'w') as js:
            js.write(f"{dumps(to_json, sort_keys=False, indent=4, ensure_ascii=False, separators=(',', ': '))}")


    def updateClick(self):
        print('Yes')
        self.ui.toolButton_9.setIcon(QIcon(f'{self.current_path}/icons/list.png'))
        self.ui.toolButton_9.setToolTip(u"Checking..")
        self.tray.setIcon(QIcon(f'{self.current_path}/icons/animevost-new.webp'))
        Thread(target = self.clicker).start()


    def clicker(self, check=True):
        urls, num = listLinkOrNumbers()
        if check:
            checkingWrite(urls, num)
        else:
            checking(urls, num)
        self.defaultIcon()


    def update(self):
        self.timer_check.start(900_000)
        self.tray.setIcon(QIcon(f'{self.current_path}/icons/animevost-new.webp'))
        print('Yes')
        Thread(target = self.clicker, args = (False,)).start()


    def timeNumber(self):
        _, num = listLinkOrNumbers()
        self.timer.start(1000)
        self.ui.lcdNumber.display(num[self.ui.comboBox.currentIndex()])
        # if self.hasFocus() == False:
            # self.hidded()
            # self.click += 1
        reads = self.uploadGlobalSettings()
        if reads['notify'] == 'unchecked':
            self.ui.toolButton_10.setIcon(QIcon(f'{self.current_path}/icons/notify.png'))
        elif reads['notify'] == 'checked':
            self.ui.toolButton_10.setIcon(QIcon(f'{self.current_path}/icons/bell.png'))



    def notifyCheck(self):
        alert = QMessageBox()
        datas = self.uploadGlobalSettings()    
        if path.exists(path.join(path.dirname(__file__), 'notify.txt')):
            with open('notify.txt', 'r') as f:
                data = f.readlines()
            str = ''
            
            for i in data:
                str = f'{str}{i}'
            
            if len(data) == 0:
                alert.setGeometry(600, 95, 300, 100)
                alert.setText("No notifications..")
            else:
                alert.setGeometry(490, 95, 300, 100)
                alert.setText(str)
                self.setGlobalSettings(datas, 'notify', 'checked')
        else:
            alert.setText('No log file..')
        alert.exec_()


    def modeColorSheme(self):
        data = self.uploadGlobalSettings()
        if self.color % 2 == 0:
            self.changeSheme('dark', 'background: rgb(49, 49, 49)', 'background: rgb(136, 136, 136)', 'color: rgb(136, 136, 136)')
            self.ui.toolButton_11.setToolTip(u"Darkmode")
            self.setGlobalSettings(data, 'mode', 'darkmode')
        else:
            self.changeSheme('lamp', 'background: rgb(255, 255, 255)', 'background: rgb(220, 220, 220)', 'color: rgb(0, 0, 0)')
            self.ui.toolButton_11.setToolTip(u"Lightmode")
            self.setGlobalSettings(data, 'mode', 'lightmode')
        self.color += 1


    def changeSheme(self, ico, win, back, color):
        self.ui.toolButton_11.setIcon(QIcon(f'{self.current_path}/icons/{ico}.png'))
        self.setStyleSheet(win)
        self.ui.label.setStyleSheet(color)
        self.ui.label_2.setStyleSheet(color)
        self.ui.lineEdit.setStyleSheet(back)
        self.ui.comboBox.setStyleSheet(back)
        self.ui.spinBox.setStyleSheet(back)
        self.ui.lcdNumber.setStyleSheet(back)



# Set Icon for toolButton
    def defaultIcon(self):
        self.tray.setIcon(QIcon(f'{self.current_path}/icons/animevost.png'))
        self.ui.toolButton_4.setIcon(QIcon(f'{self.current_path}/icons/all-click.png'))
        self.ui.toolButton_5.setIcon(QIcon(f'{self.current_path}/icons/click.png'))
        self.ui.toolButton_6.setIcon(QIcon(f'{self.current_path}/icons/lose.png'))
        self.ui.toolButton_7.setIcon(QIcon(f'{self.current_path}/icons/log.png'))
        self.ui.toolButton_8.setIcon(QIcon(f'{self.current_path}/icons/log-one.png'))
        self.ui.toolButton_9.setIcon(QIcon(f'{self.current_path}/icons/circle.png'))
        self.ui.toolButton_12.setIcon(QIcon(f'{self.current_path}/icons/checking.png'))
        # self.ui.toolButton_10.setIcon(QIcon(f'{self.current_path}/icons/bell.png'))
        self.ui.toolButton_7.setToolTip(u"Log All parse URL")
        self.ui.toolButton_8.setToolTip(u"Log One parse URL")
        self.ui.toolButton_9.setToolTip(u"Update")
        self.ui.lcdNumber.setToolTip(u"Current Series")


    def check(self):
        proc = popen('ps ax').read()
        if proc.find("chromedriver") == -1:
            return False
        else:
            print("процесс висит")
            return True


    def whileStart(self):
        while True:
            if self.check():
                self.tray.setIcon(QIcon(f'{self.current_path}/icons/dow.png'))
            else:
                self.defaultIcon()
                break
            sleep(7)


    def loging(self):
        alert = QMessageBox()
        text = ''
        if path.exists(path.join(path.dirname(__file__), 'log.txt')):
            with open('log.txt') as l:
                arr = l.readlines()
            for i in arr:
                text = f'{text}{i}'
            # text = '\n'.join(arr)
            print(text)
            alert.setText(text)
        else:
            alert.setText('No file exist...')
        alert.exec_()


    def logOne(self):
        alert = QMessageBox()
        if path.exists(path.join(path.dirname(__file__), 'loger.txt')):
            with open('loger.txt') as l:
                text = l.readline()
            alert.setText(text)
        else:
            alert.setText('No file exist...')
        alert.exec_()


    def oneDown(self):
        url, _ = listLinkOrNumbers()
        self.ui.toolButton_5.setIcon(QIcon(f'{self.current_path}/icons/spinner.png'))
        self.tray.setIcon(QIcon(f'{self.current_path}/icons/dow.png'))
        sleep(1)
        Thread(target = oneParsing, args = (url[self.ui.comboBox.currentIndex()], self.ui.lcdNumber.intValue()), name = 'Selenium-one', daemon = True).start()
        sleep(2)
        Thread(target = self.whileStart).start()


    def allDown(self):
        self.tray.setIcon(QIcon(f'{self.current_path}/icons/dow.png'))
        self.ui.toolButton_4.setIcon(QIcon(f'{self.current_path}/icons/spinner.png'))
        sleep(1)
        Thread(target = allParsing, name = 'Selenium-all', daemon = True).start()
        sleep(2)
        Thread(target = self.whileStart).start()


    def triggerFocus(self, reason):
        # elif reason == QSystemTrayIcon.MiddleClick:
        if reason == QSystemTrayIcon.Trigger:
            if self.click % 2 == 0:
                self.setFocus()
                self.show()
            else:
                self.hidded()
            self.click += 1


    def hidded(self):
        self.hide()


    def closed(self):
        extraClose()
        self.close()


    def saved(self):
        url = f'https://{self.ui.lineEdit.text()}'
        series = self.ui.spinBox.value()
        alert = QMessageBox()
        try:
            get(url)
            if url != "":
                with open('list.txt', 'a') as f:
                    f.write(f"{url},{series}\n")

                self.ui.comboBox.addItem(url)
        except:
            alert.setText(f"URL does not exist on Internet")
            alert.exec_()
            self.ui.lineEdit.setText('')


    def showed(self):
        if path.exists(path.join(path.dirname(__file__), 'name.txt')):
            with open('name.txt', 'r') as f:
                data = f.readlines()
            for i in data:
                self.ui.comboBox.addItem(i)

        reads = self.uploadGlobalSettings()
        if path.exists(path.join(path.dirname(__file__), 'notify.txt')):
            with open('notify.txt', 'r') as f:
                data = f.readlines()
            if reads['notify'] == 'unchecked':
                self.ui.toolButton_10.setIcon(QIcon(f'{self.current_path}/icons/notify.png'))
            elif reads['notify'] == 'checked':
                self.ui.toolButton_10.setIcon(QIcon(f'{self.current_path}/icons/bell.png'))

        if reads['mode'] == 'lightmode':
            self.changeSheme('lamp', 'background: rgb(255, 255, 255)', 'background: rgb(220, 220, 220)', 'color: rgb(0, 0, 0)')
            self.ui.toolButton_11.setToolTip(u"Lightmode")
            self.color = 0
        elif reads['mode'] == 'darkmode':
            self.changeSheme('dark', 'background: rgb(49, 49, 49)', 'background: rgb(136, 136, 136)', 'color: rgb(136, 136, 136)')
            self.ui.toolButton_11.setToolTip(u"Darkmode")
            self.color = 1


    def deleted(self):
        index = self.ui.comboBox.currentIndex()
        data = []
        listing = []
        del_path = path.join(path.dirname(__file__), 'list.txt')

        for i in range(self.ui.comboBox.count()):
            data.append(self.ui.comboBox.itemText(i))

        with open('list.txt', 'r') as f:
            current = f.readlines()

        for i in current:
            listing.append(i.split(','))

        del(data[index])
        del(listing[index])
        remove(del_path)

        for i in range(len(data)):
            with open('list.txt', 'a') as f:
                f.write(f"{data[i]},{listing[i][1]}")

        self.ui.comboBox.clear()
        self.showed()


app = QtWidgets.QApplication([])
application = myWindow()
# application.show()

exit(app.exec())
